// <auto-generated />
using GardenApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GardenApi.Migrations
{
    [DbContext(typeof(GardenDbContext))]
    partial class GardenDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GardenApi.Models.Plant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EndMonth")
                        .HasColumnType("int");

                    b.Property<string>("Instructions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StartMonth")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Plants");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EndMonth = 5,
                            Instructions = "Use special fertilizer.",
                            Name = "Eggplant",
                            StartMonth = 4
                        },
                        new
                        {
                            Id = 2,
                            EndMonth = 3,
                            Instructions = "Use deep planters.",
                            Name = "Carrot",
                            StartMonth = 2
                        },
                        new
                        {
                            Id = 3,
                            EndMonth = 11,
                            Instructions = "Use special fertilizer.",
                            Name = "Tulip",
                            StartMonth = 9
                        },
                        new
                        {
                            Id = 4,
                            EndMonth = 11,
                            Instructions = "Use special fertilizer.",
                            Name = "Daffodils",
                            StartMonth = 9
                        },
                        new
                        {
                            Id = 5,
                            EndMonth = 11,
                            Instructions = "Use big planters.",
                            Name = "Garlic",
                            StartMonth = 10
                        },
                        new
                        {
                            Id = 6,
                            EndMonth = 11,
                            Instructions = "Use big planters.",
                            Name = "Onions",
                            StartMonth = 10
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
